questions = {
    "What is the way we currently measure earthquakes and how do we do it": "We use moment magnitude (Mw), which is determined by the fault area that slipped, the amount of slip, and the elastic strength of the rocks involved.",
    "The seismic moment (M₀) represents the physical size and strength of an earthquake source. Which expression correctly defines it?": "M₀ = Fault Area × Amount of Slip × Elastic Strength of the Rock",
    "What are mb and ms scales": "mb measures P-wave amplitudes and saturates around M6; ms measures surface-wave amplitudes and saturates around M8. Both rely on wave amplitude, which increases 10× per magnitude unit.",
    "Whats wrong with the ricter scale": "Older Richter-type scales are based on seismic wave amplitude (each unit = 10× increase), causing them to underestimate very large earthquakes compared to moment magnitude.",
    "Explain how desert pavement forms": "Desert pavement forms as wind removes fine sediments, leaving coarse rocks behind until they create a protective surface layer that stops further erosion. Eventually the coarser rocks accumulate finer ones",
    "What are ventifacts": "Rocks that are shaped and polished by sand blasting",
    "What are yardangs": "Wind-sculpted landforms that are parallel to the wind",
    "How are dry climates/deserts defined": "It means a desert is defined by losing more water to evaporation than it gains from rain, not just by how little rain it gets.",
    "What are rainshadow deserts + example": "Rainshadow deserts form when moist air rises over mountains, rains on the windward side, and leaves the leeward side dry; the Great Basin and Mojave are examples.",
    "Explain what can happen to precipitation after it infiltrates into the ground, describing the different possible pathways and storage locations for the water.": "After infiltrating, water may stay in the shallow soil, move into nearby stream banks, sink deeper to recharge aquifers, travel long distances underground, or remain stored as groundwater.",
    "Explain the factors that influence how much precipitation infiltrates into the ground versus becoming runoff.": "Infiltration depends on the amount, intensity, and duration of precipitation; whether it falls as rain or snow; the soil type; how saturated the soil already is; the land cover; the slope of the land; and how much water plants remove through evapotranspiration.",
    "Describe where groundwater is stored and how permeability affects its movement.": "Groundwater is stored in aquifers made of porous, permeable rock or sediment, while aquitards have low permeability and slow the movement of water.",
    "What is an aquiclude, and how does it differ from other groundwater-related layers?": "An aquiclude is a layer of rock or sediment that can hold water but cannot transmit it.",
    "Explain the principles of original horizontality, lateral continuity/superpositon in sedimentary rocks": "Sedimentary rocks are deposited in layers laterally. The younger ones stack on the older ones. Igneous rocks in them are younger and were added later",
    "Explain the Principle of Cross-Cutting Relationships and the Principle of Inclusions, and describe what each tells you about the relative ages of rocks.": "INCLUSIONS are older rocks that had rocks form around them. INTRUSIONS are younger rocks that cut into an existing rock.",
    "Describe what an angular unconformity is and how the rock layers above and below it relate to each other.": "Angular uncomformity is when older rocks are tilted and eroded. Then flat newer rocks are laterally built on top.",
    "Explain what a disconformity is and how it differs from other types of unconformities.": "Disconformity is when a rock seemingly 'jumps' time periods laterally with rocks that remain parallel. It is due to erosion or non deposition",
    "What was the Great Oxygenation Event, what caused it, and when did it occur?": "A period about 2.4 billion years ago when cyanobacteria evolved oxygenic photosynthesis, releasing oxygen that began to accumulate in Earth's atmosphere.",
    "Which supercontinent was the most recent to break apart, leading to the formation of the Atlantic Ocean?": "Pangea in the msozoic era",
    "During which geologic time period were stromatolites most abundant, and what is their significance?": "Archean and Proterozoic Eons - They were formed by cyanobacteria and produced oxygen through photosynthesis.",
    "What major evolutionary event occurred during the Cambrian Period, and which fossil group is commonly associated with it?": "The Cambrian Explosion - associated with the rapid diversification of life forms, including trilobites.",
    "What event is linked to the mass extinction of the dinosaurs about 66 million years ago, and where did it": "An asteroid impact at Chicxulub on the Yucatán Peninsula in Mexico, causing drastic climate change",
    "Explain what might happen to a second well if it is drilled close enough to another well that its pumping creates a cone of depression. Why does this occur": "The nearby well may experience a lowered water table and could produce less water or even run dry. This happens because pumping from the first well draws down the water level in the aquifer, reducing the groundwater available to the second well.",
    "In coastal areas, excessive pumping of groundwater can cause saltwater intrusion. What happens when this occurs?": "Saltwater moves upward into the aquifer and mixes with the freshwater being pumped.",
    "Waves approaching the south shore of Long Island strike the beach at an angle rather than directly head-on. This causes a longshore current to form. What is the main effect of this process?": "It moves sand along the shoreline in a zigzag pattern caused by swash and backwash.",
    "Waves refract around headlands, concentrating energy on these points of land. Over time, this process:": "Causes erosion of the headlands and deposition of sediment in the bays, gradually straightening the coastline.",
    "Beaches change shape with the seasons. During winter, strong waves remove sand from the beach and deposit it offshore. During summer, gentler waves bring sand back toward the shore. What is the main reason for this seasonal change?": "Stronger winter waves erode and carry sand offshore, while calmer summer waves deposit it back on the beach.",
    "Which of the following correctly distinguishes primary from secondary porosity in sediments and rocks?": "Primary porosity represents the open space that exists at the time of deposition or rock formation, while secondary porosity develops later due to processes such as fracturing or dissolution.",
    "Permeability describes how easily a fluid can flow through a material. Which statement best explains what controls permeability in sediments and how it varies by sediment type?": "Permeability depends on the size, number, and connectivity of pores; it is highest in gravel and sand, and lowest in silt and clay.",
    "Darcy's Law describes how water flows through a porous medium. Explain the factors that control groundwater discharge and velocity according to Darcy's Law?": "The discharge (Q) increases with higher hydraulic gradient, greater cross-sectional area, and higher hydraulic conductivity; the average velocity also depends on the porosity of the material.",
    "A radioactive isotope decays to its stable daughter product with a half-life of 1 million years. After 2 half-lives, what fraction of the original parent isotope remains, and what is the parent-to-daughter ratio?": "¼ of the parent remains; parent : daughter = 1 : 3",
    "What was the Great Oxygenation Event, what caused it, and when did it occur?": "A period about 2.4 billion years ago when cyanobacteria evolved oxygenic photosynthesis, releasing oxygen that began to accumulate in Earth's atmosphere.",
    "Which supercontinent was the most recent to break apart, leading to the formation of the Atlantic Ocean?": "Pangaea - which began breaking apart during the Mesozoic Era, forming the Atlantic Ocean.",
    "During which geologic time period were stromatolites most abundant, and what is their significance?": "Archean and Proterozoic Eons - They were formed by cyanobacteria and produced oxygen through photosynthesis.",
    "What major evolutionary event occurred during the Cambrian Period, and which fossil group is commonly associated with it?": "The Cambrian Explosion - associated with the rapid diversification of life forms, including trilobites.",
    "Which statement best describes the difference between bed load and suspended load in a river?": "Bed load includes larger, heavier sand grains that move by bouncing or rolling (saltation and creep) along the surface, while suspended load consists of very fine silt and clay particles carried high and far by the wind.",
    "How does wind create cross-bedding in sand dunes?": "As wind pushes sand up the gentle windward slope and it avalanches down the steeper leeward side, forming angled layers that record wind direction.",
    "Why do subtropical steppes and deserts typically form between 20° and 30° latitude, while equatorial regions are much wetter?": "Subtropical zones are dominated by descending dry air and high-pressure systems that inhibit cloud formation, while equatorial regions have ascending moist air and low pressure that promote clouds and heavy rainfall.",
    "Why do many mid-latitude deserts and steppes form on the leeward side of mountain ranges?": "Moist air rises on the windward side, cools, and releases precipitation; by the time the air descends on the leeward side, it is dry, creating a rain shadow and arid conditions.",
    "Explain stream flow in desert environments": "Most desert streams are dry for much of the year, but during rare intense rainstorms they experience flash floods that cause rapid erosion and sediment transport.",
    "Approximately what percentage of Earth's fresh water is stored in glaciers and ice caps?": "70%",
    "During the Last Glacial Maximum, how far south did the Laurentide Ice Sheet extend?": "It advanced south of Chicago and covered the area of present-day New York City",
    "Which of the following statements correctly describes how a valley glacier moves?": "Only the ice below about 50 meters depth flows plastically; the upper brittle ice is pushed along as a rigid block.",
    "Describe the key characteristics of piedmont glaciers and the landforms they leave behind when they retreat.": "Piedmont glaciers form when valley glaciers flow onto flatter terrain and spread outward like pancake batter, creating broad lobes with visible flow-line patterns; when they retreat, they leave large, lobate moraines.",
    "Which statement best describes how a glacier's budget controls whether it advances or retreats?": "A glacier advances when winter accumulation exceeds summer melting, causing the equilibrium line (firnline) to move downslope.",
    "Which of the following best explains how glacial polish and glacial striations form on bedrock?": "They form when sediment-rich glacial ice slides over bedrock, with rock flour producing a smooth polish and larger rock fragments carving grooves.",
    "What is a tarn, and how does it form?": "A tarn is a small lake that forms in the depression of a cirque after the glacier that carved it melts.",
    "What is a cirque, and what process creates it?": "A cirque is a bowl-shaped hollow eroded at the head of a glacier by intense glacial scouring.",
    "What is a hanging valley, and why does it form?": "A hanging valley forms when a smaller tributary glacier erodes less deeply than the main glacier, leaving its valley floor elevated above the main valley.",
    "What is an arête, and how does it form?": "An arête is a sharp ridge created when two neighboring glaciers erode toward each other from opposite sides.",
    "Describe the relationship between the Ronkonkoma Moraine and the Harbor Hill Moraine on Long Island, including which one is younger and where Stony Brook University is located.": "The Harbor Hill Moraine is the younger, more northern ridge formed during the glacier's final advance, and Stony Brook University sits on this moraine.",
    "During the Last Glacial Maximum (about 18,000 years ago), global sea level was approximately how much lower than today?": "100 meters",
    "How do orbital (Milankovitch) cycles help trigger glacial and interglacial periods?": "Changes in eccentricity, axial tilt, and precession alter the amount and distribution of solar energy reaching high latitudes, influencing the growth or melting of ice sheets.",
    "Ice core data from Antarctica show temperature and atmospheric CO₂ levels over the past 400,000 years. What do these records reveal?": "CO₂ and temperature rise and fall together, with low CO₂ and low temperatures during glacial periods and high CO₂ and high temperatures during interglacial periods occurring roughly every 100,000 years.",
    "Which statement best describes the different ways sediment is transported in a river?": "Bed load consists of larger particles that move by sliding, rolling, or bouncing (saltation) along the riverbed, while suspended load is made of fine particles that stay lifted in the water, and dissolved load is material carried in solution as ions.",
    "In a meandering alluvial river, where do erosion and deposition mainly occur?": "Erosion occurs on the outer bank (cut bank), and deposition occurs on the inner bank (point bar).",
    "What is a bedrock channel?": "A bedrock channel is a river channel cut directly into solid rock, so the river mostly erodes the underlying bedrock and has very little loose sediment to shape its form.",
    "What is an alluvial channel?": "An alluvial channel is a river channel made of loose sediment (alluvium), so the river can easily erode, transport, and deposit material, allowing it to change shape more readily (meanders, point bars, braided patterns).",
    "What happens when rivers lose gradient over time": "As rivers lose gradient over time, they shift from cutting down (V-shaped valley) to cutting sideways (meanders), which eventually builds a broad floodplain with cut banks and point bars and oxbow lakes.",
    "Why do V-shaped valleys form around young rivers in mountainous regions?": "Rivers have high energy on steep slopes, so downcutting into bedrock is faster than lateral erosion, carving a narrow V-shaped valley.",
    "Incised meanders, such as those on the Colorado Plateau, form when:": "A meandering river flowing on a gentle surface later experiences uplift of the land or a drop in base level, increasing its gradient and causing the river to cut downward into its former floodplain.",
    "Stream terraces most commonly form when": "A river's base level drops, causing the river to cut down into its former floodplain and leave the old floodplain stranded as a terrace.",
    "Which statement best describes how a delta forms?": "Topset beds accumulate as flat layers near the surface, foreset beds build as sloping layers on the delta front, and the river creates new distributaries when older channels fill with sediment.",
    "What is Wave Refraction and what does it do": "Waves bend as they approach irregular shores. Energy is concentrated on headlands (causing erosion) and dispersed in bays (causing deposition), effectively straightening the coastline over time",
    "Which part of the Earth has a dense iron rich metal?\n": "The inner core of the Earth",
    "Which of the following are true about the lithosphere of the Earth?\n": "It is relatively cool, rigid shell that includes the crust and part of the mantle",
    "Which of the following is true about the continental crust of the Earth?\n": "C. It is thicker than the oceanic crust, not as dense as the oceanic crust and it ranges in thickness between 30 - 70 km. It is also ancient - up to 4 billion years old",
    "Why is the oceanic crust generally much younger than the continental crust?\n": "Because oceanic crust is constantly created at mid-ocean ridges and destroyed at subduction zones, recycling it quickly",
    "Why can the mantle partially melt even though the geothermal gradient is usually below the solidus?\n": "B. Because the mantle flows upwards while retaining the same temperature?, decompressing it and forcing it to melt The word for it is called DECOMPRESSION MELTING\n",
    "Explain how mantle convection is related to plate tectonics": "Upwelling of mantle and decompression melting happens at the mid-ocean ridges (divergent plate boundary) and downwelling and subduction happens at the ocean-ocean or ocean-continent convergent plate boundaries. The lithospheric plates move over the top of a weak asthenosphere layer",
    "Explain how magma is formed at convergent boundaries?": "Magma is formed when water-rich minerals interact with the mantle, increasing volatility and decreasing the temperature necessary to melt. This is called FLUX MELTING",
    "Explain how the downwelling zones contributed to the movement of the plates": "The downwelling zones (involving sinking lithospheric slabs) results in SLAB PULL FORCES, which help to move the plates",
    "Explain the movement rate of the plates": "The lithospheric plates move slowly, at the rate of cm/year, which is about the rate that fingernails grow",
    "What is subduction": "Subduction is the process where one lithospheric plate collides with another one and sinks down into the mantle. This only happens to oceanic plates because it is denser than the mantle",
    "Explain the 3 types of plate boundaries for earthquakes": "1. Convergent boundaries: where plates collide, causing subduction or mountain building.\n"
    "2. Divergent boundaries: where plates move apart, creating new crust as magma rises.\n"
    "3. Transform boundaries: where plates slide past each other, leading to friction and earthquakes.",
    "An example of a transform plate boundary is": "The San Andreas Fault in California where the Pacific Plate is moving horizontally along the transform fault relative to North America. No, California is not going to fall off into the ocean.",
    "An example of a convergent plate boundary is": "The Andes Mountains in South America where the oceanic Nazca Plate is subducting or The Himalaya Mountains involving India-Eurasia motion",
    "An example of a divergent plate boundary is": "The Mid-Atlantic Ridge where the Eurasian and North American plates are moving apart",
    "Explain how the polarity of the seafloor provides evidence for seafloor spreading.": "The alternating polarity of the seafloor, recorded as stripes on either side of the mid-ocean ridge, shows that new crust is continuously formed and pushed outward.",
    "What does analyzing the polarity of the seafloor reveal about Earth's magnetic field?": "It shows that Earth's magnetic field has reversed many times throughout history, flipping between normal and reversed polarity.",
    "How can scientists determine if two sections of the seafloor are the same age using the mid-ocean ridge?": "If the two sections are the same distance from the mid-ocean ridge, they are the same age.",
    "What minerals is New Mexico's Hansonburg District best known for producing": "Fluorite and barite, with world-class linarite",
    "Which basic building block makes up all silicate minerals": "Silicon-oxygen tetrahedron",
    "Pyroxenes are made of silica tetrahedra linked together in what pattern?": "Single chains",
    "Which mineral group includes halite (NaCl) and fluorite (CaF₂)": "Halides",
    "Amphiboles differ from pyroxenes because their silica tetrahedra are arranged as": "Double chains",
    "What is the source of the large cyrstals of light-colored minerals in granite?": "Slow cooling of molten rock deep beneath the surface",
    "What is the source of the small cyrstals in basalt?": "The rapid cooling of the mineral on the surface",
    "What is the oceanic crust largely made of": "Basalt",
    "How does magma turn into igneous rock": "Cooling and crystalizing at volcanoes",
    "What are the two main types of igneous rock that can form": "Extrusive (rapid cooling) like obsidian and basalt and intrusive (slow cooling) like granite",
    "How are metamorphic rocks formed and from which type": "Sedimentary rocks are exposed to heat and pressure low in the crust to create metamorphoic rocks",
    "Explain the transition of igneous to sedimentary": "Weathering will break down igenous rocks and turn it into sediment",
    "Describe Ionic Bonding": "Chemical bond formed by the electrostatic attraction between oppositely charged ions, resulting from the permanent transfer of one or more electrons from one atom to another",
    "Describe Covalent Bonding": "Covalent bonds share electrons between ions to complete their valence shells.",
    "What is the base of all silicate minerals, what type of bond is it, and is it positive or negtive": "The silicon-oxygen tetrahedron, covalent bonds, and -4 charge",
    "What is the structure of silicia tetrahedra of olivines? What is the clevage?": "Olivines are single, no-chain tetrahedrons. They have no clevage",
    "What is the structure of silica tetrahedrea of pyroxene, where is it found, what is its color, and which rocks are pyroxenes?": "Pyroxenes are single-chain structures, they are found in mafic igenous rocks, they are dark green to black, and examples are peridotite and basalt",
    "What is the structure of silica tetrahedrea of amphibole, where is it found, what is its color, and which rocks are amphiboles?": "Amphiboles are double-chained structures, they are found in igneous and metamorphic rocks, they are usually black but come in a variety of colors, and you can find them in diorite and amphibolite (hornblende)",
    "What is the structure of silica tetrahedrea of sheet silicates, where is it found, what is its color, and which rocks are sheet silicates?": "Sheet silicates share three oxygen atoms with neighbots (out of 4), making flat sheets. They form micas and clay minerals. Micas like biotite in granite and muscovite in schist are found in igneous and metamorphic rocks. Clay minerals are found in sedimentary rocks",
    "What is the mica sandwich": "Cations (positively charged ions) are sandwiched between silicate tetrahedra sheets, weakly holding them together.",
    "What are the two most abundant minerals in the continental crust?": "Quartz and feldspar",
    "What is the structure of silicia tetrahedrea in Quartz and feldspar?": "Quartz and feldspar share all 4 corners of their oxygens with other tetrahedra",
    "What are the most frequently occuring carbonate minerals and where are they found?": "Calcite and dolomite, found in sedminetary rocks like limestone and dolostone rocks",
    "How are oxides formed and what is the most familiar oxide": "Oxides are formed when metal ions bond covalently with oxygen, with rust being an example",
    "What are halides? What are the 2 parts of a halide and what are examples": "Halides are when the minerals flourine, chlorine, and some others bond with a positively charged metal. Examples are halite (NaCl), Sylvite (KCl), and flourite (CaF2)",
    "What are sulfides made of and what are examples": "Sulfides are just metal bonded with sulfur. Examples are Pyrite (fools gold), Galena (lead sulfide), and chalcopyrite (iron-copper sulfide)",
    "Why are sulfides important for mining?": "Sulfides tend to be the main ore minerals for certain elements. Galena (lead suflfide) is the main source of lead, and chalcopyrite(iron-copper sulfide) is the main source of copper. Other minerals include nickel, mercury, aresenic, molybdenum, and and antimony",
    "What are sulfate minerals and where are they used": "Sulfate minerals are sulfate ions (sulfur and oxygen) combined with a metal ion. We use them in construction like plaster and drywall through Gypsum (CaSO4 * 2H20)",
    "What contributes to whether a mineral is usually found in a pure state in the wild?": "How reactive it is and likely to bond to other minerals. Gold is very unlikely to bond to other minerals",
    "What is luster in minerals?": "Luster is how reflective a mineral is",
    "What are the 2 kinds of luster": "Shiny metallic luster in pyrite and galena. Submetallic luster dull from tarnish.",
    "What kind of luster are Quartz crystals?": "Vitreous (glassy) luster",
    "What is streak": "The color of a powdered verion of a mineral",
    "What are the major mineral properties": "Crystal shape/habit, hardness, clevage",
    "What are minerals considered to be in geology?": "The building blocks of rocks",
    "Which set of characteristics is commonly used to identify minerals in the field or lab?": "Luster, streak, hardness, cleavage, fracture",
    "Which group of minerals is the largest on Earth by both variety and quantity?": "Silicates",
    "What are the two most abundant elements in Earth's crust and mantle that form the basis of silicate minerals?": "Silicon and oxygen",
    "Where does magma typically form in relation to plate tectonics?": "At divergent boundaries, subduction zones, and hotspots",
    "What does Phaneritic mean for cooling history?": "Slow cooling deep underground (intrusive/plutonic). Crystals have lots of time to grow large. Coarse mineral like granite",
    "What does Aphanitic mean for cooling history?": "Rapid cooling at or near the surface (extrusive/volcanic). Crystals are too small to see without a microscope like basalt",
    "What does Glassy mean for cooling history": "Rapid cooling at or near the surface (extrusive/volcanic). Crystals are too small to see without a microscope like obsidian",
    "What is the cooling history of Porphyritic": "Cooling history: Two-stage cooling — slow cooling first (large crystals/phenocrysts form), followed by rapid cooling (fine matrix/groundmass forms) like andesite",
    "How does silica content affect magma viscosity and eruptive style?": "More silica → higher viscosity → more explosive eruptions",
    "What is Phaneritic texture and how do you get it": "Phaneritic texture is coarse, large crystals caused by slow cooling",
    "What are the silica levels of ultramafic, mafic, intermediate, and felsic?": "ultramafic: 38-45 mafic ~ 40-50, intermediate ~ 50-60, felsic ~60-70",
    "Example of ultramafic Phaneritic rocks": "Peridotite",
    "Example of mafic phaneritic rocks": "Gabbro",
    "Example of intermediate phaneritic rocks": "Diorite",
    "Example of felsic phaneritic rocks": "Granite",
    "Explain Aphanitic texture": "Low-no crystals, rapid cooling",
    "Example of ultramafic Phaneritic rocks": "Komatiite",
    "Example of mafic phaneritic rocks": "Basalt",
    "Example of intermediate phaneritic rocks": "Andesite",
    "Example of felsic phaneritic rocks": "Rhyolite",
    "What is the melting order of Bowen's reaction series from soonest to latest?": "Olivines, pyroxines, amphiboles, biotite",
    "Where do calderas come from": "calderas are formed when a volcano erupts and loses a large portion of its magma, causing the structure to collapse",
    "What best defines a Hot Spot track": "The motion of a plate over a mantle plume that is fixed in place and that originates in the lower mantle, resulting in a track of volcanos that are progressively older as distances increase away from the hotspot",
    "What is frost wedging": "When ice enters a crack, freezes, and expands. Spreading the rock",
    "What is sheeting": "Reduction of pressure on a rock's surface causes it to become unable to support its weight and expand, eventually peeling off",
    "What is biological weathering": "Biological growth (like a tree) grows into a rock base, widening cracks.",
    "Which statement best explains why many sedimentary rocks and soils have a reddish color?": "They contain iron-bearing minerals that oxidize, forming rust-like iron oxides.",
    "How does hydrolysis of silicate minerals help remove CO₂ from the atmosphere?": "carbon combines with water, forms carbonic acid. This acid reacts with sillicate minerals to turn into ions. These ions, dissolved in water, then turn into rocks.",
    "Why does mechanical weathering (physical breakup of rocks into smaller pieces) accelerate chemical weathering?": "Breaking rocks into smaller fragments increases total surface area, allowing more contact with water and air.",
    "What is Chemical Weathering": "When minerals are aletered and destroyed by coming in contact with water solutions and/or air",
    "What is the main CO2 drawdown mechanism in earth's long-term carbon cycle": "Hydrolosis",
    "What is hydrolosis": "water splits minerals into smaller, sometimes different minerals. It often releases dissolved ions",
    "What is dissolution": "A process where a mineral dissolves completely into its ionic components in water, without forming a new solid mineral. Everything goes into the solution",
    "What is oxidation": "When iron-bearing minerals react with water and oxygen, creating iron oxides",
    "What is spheroidal chemical weathering": "When highly angled rocks are smoothed out over time",
    "What is differential chemical weathering?": "Differential chemical weathering occurs when different minerals or rocks within the same area weather at different rates due to variations in their chemical composition and resistance to weathering processes.",
    "What are clastic products?": "Clastic are solid residues of minerals that did not break down, or newly formed solid minerals",
    "What are biochemical products?": "Biochemical products form when dissolved minerals released by chemical weathering are later used by living organisms to build shells or skeletons, which eventually become biochemical sedimentary rocks after lithification.",
    "What is diagenesis and what are the 2 main forms of it": "Diagenesis is all the physical, chemical, and biological processes that transform sediment into sedimentary rock. Includes Lithifcation and Recrystalllization",
    "What is lithification": "sediments become solid rock by compaction (compression) and cementation (grains attached by natural cement, such as: calcite, silica, and iron oxide).",
    "What is recystallization": "development of more stable minerals from less stable ones. Part of metamorphosis under high pressure without melting.",
    "What are detrial rocks": "rocks where the source is transported sediment as solid particles",
    "What are chemical rocks": "rocks where the source is sediment precipitated from a solution",
    "How do detrial rocks relate to the energy of a system? What order is conglomerate sandstone and shale in energy": "The larger the grain in detrial rocks the higher the energy of the system. From high to low energy its Conglomerate -> Sandstone -> Shale",
    "What are clastic chemical rocks": "Composed of fragments of silicate minerals, particles, shells etc",
    "What are nonclastic chemical rocks": "Rocks formed through crystallization (also known as chemical precipiation) or biological processes",
    "What is metamorphic rock foliation": " Foliation is the result of the parallel arrangement of minerals in a plane perpendicular to the maximum principal applied stress",
    "What is the order of metamorphic grade from lowest temp/pressure to highest": "shale, slate, phyllite, schist, gneiss",
    "Why does Gneiss sometimes have igenous rock in it?": "The temperature is so high that an introduction to water can cause melt that forms igneous rocks along the metamorphic rocks",
    "What are the three index minerals from lowest temperature/pressure to highest": "andalusite, kyanite, and sillimanite",
    "What is soil composition": r"45% mineral matter, 25% air, 25% water, 5% organic matter",
    "What is ductile deformation": "Usually when pieces are hot, they warp and cannot be fit back together",
    "What is elastic deformation": "Deformation that can be returned to original shape when stress is removed",
    "What is brittle deformation": "Deformation where pieces snap. Usually after elastic. Technically the pieces could be fit bach together",
    "Which deformation causes earthquakes": "brittle deformation",
    "Which deformation happens shallower/deeper": "elastic/brittle shallower, ductile deeper",
    "Which statement best describes the relationship between Bowen's Reaction Series and mineral stability during weathering?": "Minerals that crystallize first at high temperature (e.g., olivine, pyroxene) are the least stable at Earth's surface and weather the fastest.",
    "Assuming a typical geothermal gradient of about 30 °C per km and a pressure increase of ~3 kbar per 10 km, at what approximate depth would amphibolite-grade metamorphism (550-700 °C, 5-8 kbar) occur?": "20-25",
    "Which sequence correctly represents the increasing metamorphic grade (temperature and pressure) of regional metamorphism?": "Greenschist → Amphibolite → Granulite",
    "What is the hypocenter/focus?": "The focus (hypocenter) is the point within the Earth where rupture and seismic waves first originate.",
    "What is the epicenter": "the epicenter is the surface directly above the hypocenter",
    "describe the motion and tectonic setting of normal and reverse (thrust) faults": "A normal fault forms when the hanging wall moves down relative to the footwall during horizontal crustal extension, while a reverse (thrust) fault forms when the hanging wall moves up relative to the footwall during horizontal crustal contraction.",
    "What is a strike-slip fault": "Blocks move horizontally past each other along a nearly vertical fault, accommodating horizontal shear. Shear stress at transform boundaries",
    "What are normal faults": "When a hanging wall moves DOWN relative to footwall. Usually its tension stress at divergent boundaries.",
    "What are thrust/reverse faults": "When a hanging wall moves UP relative to footwall. Usually its compression stress at convergent boundaries",
    "Example of a strike-slip fault?": "Fault in California",
    "At what approximate depth do rocks in the continental crust begin to behave ductilely rather than brittlely, assuming a geothermal gradient of 30 °C per km and a transition temperature near 450 °C?": "~15 km — where temperatures reach about 450 °C",
    "Which statement correctly describes the main types and behaviors of seismic waves?": "P-waves are the fastest body waves and arrive first; S-waves are slower body waves that arrive second; surface waves (Love and Rayleigh) travel along Earth's surface, are slowest, and cause the most destruction.",
    "Explain how P waves move": "P-waves (primary) compress and expand material in the same direction they travel (longitudinal motion) and move through solids, liquids, and gases",
    "Explain how S waves move": "S-waves (secondary) move particles up and down or side to side (transverse motion) and only travel through solids.",
    "Explain how Love waves work": "Love waves move the ground side to side horizontally and cause severe surface shaking.",
    "Explain how Rayleigh waves work": "Rayleigh waves produce circular or rolling motion (like ocean waves) that affects both vertical and horizontal ground movement",
    "what are Seismometers and how do they work": "they work by attatching a device to a spring. When the ground shakes the device shakes and the mass stays still and we record relative motion",
    "What are mb and ms scales": "mb: body-wave magnitude scales that measure P waves saturates (caps out) at around magnitude 6. ms: Detects amplitude of surface waves (rayleigh). Saturates (caps out) at magnitude 8",
    "Whats wrong with the ricter scale": "older Richter-type scales underestimate the size of very large earthquakes",
    "What is the way we currently measure earthquakes and how do we do it": "We use moment magnitude (Mw) and it uses the fault area that slipped, the amount of slip, and the elastic strength of the rocks involved. ",
    "The seismic moment (M₀) represents the physical size and strength of an earthquake source. Which expression correctly defines it?": "MO = Fault Area x Amount of Slip x Elastic Strength of Rock",
    "How do we tell the distance of an earthquake?": "The difference in S-P arrival times at a station gives the distance to the epicenter",
    "How do we tell where an earthquake is?": "We tell where an earthquake is by measuring the distance of the earthquake from at least 3 different locations then triangulate",
    "What is the S wave shadow zone?": "S waves can only travel through solids, so they stop at the liquid outer core. This makes shadow zones at about 105° and 180° from the earthquake's focus",
    "What is the Mercalli Intensity Scale": "Mercalli Intensity Scale measures an earthquake's effects on people, buildings, and the environment. Its measured from Ranges from I (not felt) to XII (total destruction)",
    "The Modified Mercalli Intensity (MMI) scale measures earthquake shaking based on observed effects and human perception. For earthquakes of similar magnitude, why are felt intensities often higher and experienced over larger areas in the central and eastern United States than in the western United States?": "Because cooler, older, less-fractured crust in the central and eastern U.S. transmits seismic energy more efficiently, while hotter, more fractured crust in the tectonically active western U.S. absorbs and scatters energy more rapidly.",
    "During strong earthquakes, liquefaction can cause buildings and other structures to tilt or sink. What best explains how this process occurs?": "Water-saturated, loose sediments lose strength as pore water pressure increases, causing the ground to behave like a liquid.",
    "Large tsunamis are most commonly generated by megathrust earthquakes at subduction zones. How does this type of earthquake produce a tsunami?": "The hanging wall of a thrust fault suddenly uplifts the seafloor during rupture, displacing the overlying column of water and generating waves that radiate outward.",
}